### PR TITLE
Switch from `appdirs` (deprecated) to `platformdirs`

### LINKED ISSUE #760: Magic-Folder depends on deprecated `appdirs` package
As per https://github.com/ActiveState/appdirs, the `appdirs` package (which is currently used by magic-folder but has not seen a release since 2020) is officially deprecated:

>Note: This project has been officially deprecated. You may want to check out https://pypi.org/project/platformdirs/ which is a more active fork of appdirs.

### PR DESCRIPTION
**Pull request by crwood**
Closes #760

### CODE REVIEW

**Comment by crwood** [comment]
The `integration tests (... master)` jobs appear to be failing due to (upstream?) issues with building Tahoe-LAFS wheels:

>WARNING: Built wheel for tahoe-lafs is invalid: Wheel has unexpected file name: expected '0.0.0', got '1.19.0.post190'
>ERROR: Could not build wheels for tahoe-lafs, which is required to install pyproject.toml-based projects

**Comment by meejah** [comment]
Can repeat, do not know what that means. Some ... packaging schmoo? ... I think this is "tahoe-lafs master"'s fault though?

**Comment by hacklschorsch** [comment]
I fixed this for the Tahoe-LAFS CircleCI Windows jobs in https://github.com/tahoe-lafs/tahoe-lafs/pull/1383.

Specifically https://github.com/tahoe-lafs/tahoe-lafs/pull/1383/commits/0d196efc31d2f10dad146af563eaa05e84e9d88d makes it so the `_version.py` file is around for the later steps even if we use the cached wheels in the first step.

I also had to bust the CI cache so the job wouldn't use the invalid wheel in it anymore (in https://github.com/tahoe-lafs/tahoe-lafs/pull/1383/commits/151cd2b13aec6d453850133898cc890c839e2dcc)

**Comment by crwood** [comment]
Thank you for the extra info/context, @hacklschorsch 

>I think this is "tahoe-lafs master"'s fault though?

As per #762, we can see the [same failures](https://github.com/tahoe-lafs/magic-folder/actions/runs/12071233706/job/33662523792?pr=762) occurring in a separate, trivial PR (just to further confirm/demonstrate that the issue lies with Tahoe-LAFS -- and that it isn't _this PR_ that's introducing the failure).

**Comment by crwood** [comment]
The artifact name-conflicts should now be fixed.

**Pull request merged**
